// Code generated by ent, DO NOT EDIT.

package checkinrewardtier

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the checkinrewardtier type in the database.
	Label = "check_in_reward_tier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldMatchType holds the string denoting the match_type field in the database.
	FieldMatchType = "match_type"
	// FieldMatchThreshold holds the string denoting the match_threshold field in the database.
	FieldMatchThreshold = "match_threshold"
	// FieldMinReward holds the string denoting the min_reward field in the database.
	FieldMinReward = "min_reward"
	// FieldMaxReward holds the string denoting the max_reward field in the database.
	FieldMaxReward = "max_reward"
	// FieldBaseCap holds the string denoting the base_cap field in the database.
	FieldBaseCap = "base_cap"
	// FieldBetaMin holds the string denoting the beta_min field in the database.
	FieldBetaMin = "beta_min"
	// FieldBetaMax holds the string denoting the beta_max field in the database.
	FieldBetaMax = "beta_max"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the checkinrewardtier in the database.
	Table = "checkin_reward_tiers"
)

// Columns holds all SQL columns for checkinrewardtier fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEnabled,
	FieldMatchType,
	FieldMatchThreshold,
	FieldMinReward,
	FieldMaxReward,
	FieldBaseCap,
	FieldBetaMin,
	FieldBetaMax,
	FieldSortOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultMatchType holds the default value on creation for the "match_type" field.
	DefaultMatchType string
	// MatchTypeValidator is a validator for the "match_type" field. It is called by the builders before save.
	MatchTypeValidator func(string) error
	// DefaultMatchThreshold holds the default value on creation for the "match_threshold" field.
	DefaultMatchThreshold float64
	// DefaultMinReward holds the default value on creation for the "min_reward" field.
	DefaultMinReward float64
	// DefaultMaxReward holds the default value on creation for the "max_reward" field.
	DefaultMaxReward float64
	// DefaultBaseCap holds the default value on creation for the "base_cap" field.
	DefaultBaseCap float64
	// DefaultBetaMin holds the default value on creation for the "beta_min" field.
	DefaultBetaMin float64
	// DefaultBetaMax holds the default value on creation for the "beta_max" field.
	DefaultBetaMax float64
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CheckInRewardTier queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByMatchType orders the results by the match_type field.
func ByMatchType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchType, opts...).ToFunc()
}

// ByMatchThreshold orders the results by the match_threshold field.
func ByMatchThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchThreshold, opts...).ToFunc()
}

// ByMinReward orders the results by the min_reward field.
func ByMinReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinReward, opts...).ToFunc()
}

// ByMaxReward orders the results by the max_reward field.
func ByMaxReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxReward, opts...).ToFunc()
}

// ByBaseCap orders the results by the base_cap field.
func ByBaseCap(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseCap, opts...).ToFunc()
}

// ByBetaMin orders the results by the beta_min field.
func ByBetaMin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBetaMin, opts...).ToFunc()
}

// ByBetaMax orders the results by the beta_max field.
func ByBetaMax(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBetaMax, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
