// Code generated by ent, DO NOT EDIT.

package checkinrewardtier

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldEnabled, v))
}

// MatchType applies equality check predicate on the "match_type" field. It's identical to MatchTypeEQ.
func MatchType(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldMatchType, v))
}

// MatchThreshold applies equality check predicate on the "match_threshold" field. It's identical to MatchThresholdEQ.
func MatchThreshold(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldMatchThreshold, v))
}

// MinReward applies equality check predicate on the "min_reward" field. It's identical to MinRewardEQ.
func MinReward(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldMinReward, v))
}

// MaxReward applies equality check predicate on the "max_reward" field. It's identical to MaxRewardEQ.
func MaxReward(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldMaxReward, v))
}

// BaseCap applies equality check predicate on the "base_cap" field. It's identical to BaseCapEQ.
func BaseCap(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldBaseCap, v))
}

// BetaMin applies equality check predicate on the "beta_min" field. It's identical to BetaMinEQ.
func BetaMin(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldBetaMin, v))
}

// BetaMax applies equality check predicate on the "beta_max" field. It's identical to BetaMaxEQ.
func BetaMax(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldBetaMax, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldEnabled, v))
}

// MatchTypeEQ applies the EQ predicate on the "match_type" field.
func MatchTypeEQ(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldMatchType, v))
}

// MatchTypeNEQ applies the NEQ predicate on the "match_type" field.
func MatchTypeNEQ(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldMatchType, v))
}

// MatchTypeIn applies the In predicate on the "match_type" field.
func MatchTypeIn(vs ...string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldMatchType, vs...))
}

// MatchTypeNotIn applies the NotIn predicate on the "match_type" field.
func MatchTypeNotIn(vs ...string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldMatchType, vs...))
}

// MatchTypeGT applies the GT predicate on the "match_type" field.
func MatchTypeGT(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldMatchType, v))
}

// MatchTypeGTE applies the GTE predicate on the "match_type" field.
func MatchTypeGTE(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldMatchType, v))
}

// MatchTypeLT applies the LT predicate on the "match_type" field.
func MatchTypeLT(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldMatchType, v))
}

// MatchTypeLTE applies the LTE predicate on the "match_type" field.
func MatchTypeLTE(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldMatchType, v))
}

// MatchTypeContains applies the Contains predicate on the "match_type" field.
func MatchTypeContains(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldContains(FieldMatchType, v))
}

// MatchTypeHasPrefix applies the HasPrefix predicate on the "match_type" field.
func MatchTypeHasPrefix(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldHasPrefix(FieldMatchType, v))
}

// MatchTypeHasSuffix applies the HasSuffix predicate on the "match_type" field.
func MatchTypeHasSuffix(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldHasSuffix(FieldMatchType, v))
}

// MatchTypeEqualFold applies the EqualFold predicate on the "match_type" field.
func MatchTypeEqualFold(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEqualFold(FieldMatchType, v))
}

// MatchTypeContainsFold applies the ContainsFold predicate on the "match_type" field.
func MatchTypeContainsFold(v string) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldContainsFold(FieldMatchType, v))
}

// MatchThresholdEQ applies the EQ predicate on the "match_threshold" field.
func MatchThresholdEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldMatchThreshold, v))
}

// MatchThresholdNEQ applies the NEQ predicate on the "match_threshold" field.
func MatchThresholdNEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldMatchThreshold, v))
}

// MatchThresholdIn applies the In predicate on the "match_threshold" field.
func MatchThresholdIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldMatchThreshold, vs...))
}

// MatchThresholdNotIn applies the NotIn predicate on the "match_threshold" field.
func MatchThresholdNotIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldMatchThreshold, vs...))
}

// MatchThresholdGT applies the GT predicate on the "match_threshold" field.
func MatchThresholdGT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldMatchThreshold, v))
}

// MatchThresholdGTE applies the GTE predicate on the "match_threshold" field.
func MatchThresholdGTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldMatchThreshold, v))
}

// MatchThresholdLT applies the LT predicate on the "match_threshold" field.
func MatchThresholdLT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldMatchThreshold, v))
}

// MatchThresholdLTE applies the LTE predicate on the "match_threshold" field.
func MatchThresholdLTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldMatchThreshold, v))
}

// MinRewardEQ applies the EQ predicate on the "min_reward" field.
func MinRewardEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldMinReward, v))
}

// MinRewardNEQ applies the NEQ predicate on the "min_reward" field.
func MinRewardNEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldMinReward, v))
}

// MinRewardIn applies the In predicate on the "min_reward" field.
func MinRewardIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldMinReward, vs...))
}

// MinRewardNotIn applies the NotIn predicate on the "min_reward" field.
func MinRewardNotIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldMinReward, vs...))
}

// MinRewardGT applies the GT predicate on the "min_reward" field.
func MinRewardGT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldMinReward, v))
}

// MinRewardGTE applies the GTE predicate on the "min_reward" field.
func MinRewardGTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldMinReward, v))
}

// MinRewardLT applies the LT predicate on the "min_reward" field.
func MinRewardLT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldMinReward, v))
}

// MinRewardLTE applies the LTE predicate on the "min_reward" field.
func MinRewardLTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldMinReward, v))
}

// MaxRewardEQ applies the EQ predicate on the "max_reward" field.
func MaxRewardEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldMaxReward, v))
}

// MaxRewardNEQ applies the NEQ predicate on the "max_reward" field.
func MaxRewardNEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldMaxReward, v))
}

// MaxRewardIn applies the In predicate on the "max_reward" field.
func MaxRewardIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldMaxReward, vs...))
}

// MaxRewardNotIn applies the NotIn predicate on the "max_reward" field.
func MaxRewardNotIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldMaxReward, vs...))
}

// MaxRewardGT applies the GT predicate on the "max_reward" field.
func MaxRewardGT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldMaxReward, v))
}

// MaxRewardGTE applies the GTE predicate on the "max_reward" field.
func MaxRewardGTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldMaxReward, v))
}

// MaxRewardLT applies the LT predicate on the "max_reward" field.
func MaxRewardLT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldMaxReward, v))
}

// MaxRewardLTE applies the LTE predicate on the "max_reward" field.
func MaxRewardLTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldMaxReward, v))
}

// BaseCapEQ applies the EQ predicate on the "base_cap" field.
func BaseCapEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldBaseCap, v))
}

// BaseCapNEQ applies the NEQ predicate on the "base_cap" field.
func BaseCapNEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldBaseCap, v))
}

// BaseCapIn applies the In predicate on the "base_cap" field.
func BaseCapIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldBaseCap, vs...))
}

// BaseCapNotIn applies the NotIn predicate on the "base_cap" field.
func BaseCapNotIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldBaseCap, vs...))
}

// BaseCapGT applies the GT predicate on the "base_cap" field.
func BaseCapGT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldBaseCap, v))
}

// BaseCapGTE applies the GTE predicate on the "base_cap" field.
func BaseCapGTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldBaseCap, v))
}

// BaseCapLT applies the LT predicate on the "base_cap" field.
func BaseCapLT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldBaseCap, v))
}

// BaseCapLTE applies the LTE predicate on the "base_cap" field.
func BaseCapLTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldBaseCap, v))
}

// BetaMinEQ applies the EQ predicate on the "beta_min" field.
func BetaMinEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldBetaMin, v))
}

// BetaMinNEQ applies the NEQ predicate on the "beta_min" field.
func BetaMinNEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldBetaMin, v))
}

// BetaMinIn applies the In predicate on the "beta_min" field.
func BetaMinIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldBetaMin, vs...))
}

// BetaMinNotIn applies the NotIn predicate on the "beta_min" field.
func BetaMinNotIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldBetaMin, vs...))
}

// BetaMinGT applies the GT predicate on the "beta_min" field.
func BetaMinGT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldBetaMin, v))
}

// BetaMinGTE applies the GTE predicate on the "beta_min" field.
func BetaMinGTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldBetaMin, v))
}

// BetaMinLT applies the LT predicate on the "beta_min" field.
func BetaMinLT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldBetaMin, v))
}

// BetaMinLTE applies the LTE predicate on the "beta_min" field.
func BetaMinLTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldBetaMin, v))
}

// BetaMaxEQ applies the EQ predicate on the "beta_max" field.
func BetaMaxEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldBetaMax, v))
}

// BetaMaxNEQ applies the NEQ predicate on the "beta_max" field.
func BetaMaxNEQ(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldBetaMax, v))
}

// BetaMaxIn applies the In predicate on the "beta_max" field.
func BetaMaxIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldBetaMax, vs...))
}

// BetaMaxNotIn applies the NotIn predicate on the "beta_max" field.
func BetaMaxNotIn(vs ...float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldBetaMax, vs...))
}

// BetaMaxGT applies the GT predicate on the "beta_max" field.
func BetaMaxGT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldBetaMax, v))
}

// BetaMaxGTE applies the GTE predicate on the "beta_max" field.
func BetaMaxGTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldBetaMax, v))
}

// BetaMaxLT applies the LT predicate on the "beta_max" field.
func BetaMaxLT(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldBetaMax, v))
}

// BetaMaxLTE applies the LTE predicate on the "beta_max" field.
func BetaMaxLTE(v float64) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldBetaMax, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CheckInRewardTier) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CheckInRewardTier) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CheckInRewardTier) predicate.CheckInRewardTier {
	return predicate.CheckInRewardTier(sql.NotPredicates(p))
}
