// Code generated by ent, DO NOT EDIT.

package checkinrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the checkinrecord type in the database.
	Label = "check_in_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCheckInDate holds the string denoting the check_in_date field in the database.
	FieldCheckInDate = "check_in_date"
	// FieldRewardAmount holds the string denoting the reward_amount field in the database.
	FieldRewardAmount = "reward_amount"
	// FieldStreakCount holds the string denoting the streak_count field in the database.
	FieldStreakCount = "streak_count"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldRechargeSnapshot holds the string denoting the recharge_snapshot field in the database.
	FieldRechargeSnapshot = "recharge_snapshot"
	// FieldUsageSnapshot holds the string denoting the usage_snapshot field in the database.
	FieldUsageSnapshot = "usage_snapshot"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the checkinrecord in the database.
	Table = "check_in_records"
)

// Columns holds all SQL columns for checkinrecord fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldCheckInDate,
	FieldRewardAmount,
	FieldStreakCount,
	FieldScore,
	FieldRechargeSnapshot,
	FieldUsageSnapshot,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRewardAmount holds the default value on creation for the "reward_amount" field.
	DefaultRewardAmount float64
	// DefaultStreakCount holds the default value on creation for the "streak_count" field.
	DefaultStreakCount int
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore float64
	// DefaultRechargeSnapshot holds the default value on creation for the "recharge_snapshot" field.
	DefaultRechargeSnapshot float64
	// DefaultUsageSnapshot holds the default value on creation for the "usage_snapshot" field.
	DefaultUsageSnapshot float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CheckInRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCheckInDate orders the results by the check_in_date field.
func ByCheckInDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckInDate, opts...).ToFunc()
}

// ByRewardAmount orders the results by the reward_amount field.
func ByRewardAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardAmount, opts...).ToFunc()
}

// ByStreakCount orders the results by the streak_count field.
func ByStreakCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreakCount, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByRechargeSnapshot orders the results by the recharge_snapshot field.
func ByRechargeSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeSnapshot, opts...).ToFunc()
}

// ByUsageSnapshot orders the results by the usage_snapshot field.
func ByUsageSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageSnapshot, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
