// Code generated by ent, DO NOT EDIT.

package checkinrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldUserID, v))
}

// CheckInDate applies equality check predicate on the "check_in_date" field. It's identical to CheckInDateEQ.
func CheckInDate(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldCheckInDate, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldRewardAmount, v))
}

// StreakCount applies equality check predicate on the "streak_count" field. It's identical to StreakCountEQ.
func StreakCount(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldStreakCount, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldScore, v))
}

// RechargeSnapshot applies equality check predicate on the "recharge_snapshot" field. It's identical to RechargeSnapshotEQ.
func RechargeSnapshot(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldRechargeSnapshot, v))
}

// UsageSnapshot applies equality check predicate on the "usage_snapshot" field. It's identical to UsageSnapshotEQ.
func UsageSnapshot(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldUsageSnapshot, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldUserID, v))
}

// CheckInDateEQ applies the EQ predicate on the "check_in_date" field.
func CheckInDateEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldCheckInDate, v))
}

// CheckInDateNEQ applies the NEQ predicate on the "check_in_date" field.
func CheckInDateNEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldCheckInDate, v))
}

// CheckInDateIn applies the In predicate on the "check_in_date" field.
func CheckInDateIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldCheckInDate, vs...))
}

// CheckInDateNotIn applies the NotIn predicate on the "check_in_date" field.
func CheckInDateNotIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldCheckInDate, vs...))
}

// CheckInDateGT applies the GT predicate on the "check_in_date" field.
func CheckInDateGT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldCheckInDate, v))
}

// CheckInDateGTE applies the GTE predicate on the "check_in_date" field.
func CheckInDateGTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldCheckInDate, v))
}

// CheckInDateLT applies the LT predicate on the "check_in_date" field.
func CheckInDateLT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldCheckInDate, v))
}

// CheckInDateLTE applies the LTE predicate on the "check_in_date" field.
func CheckInDateLTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldCheckInDate, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldRewardAmount, v))
}

// StreakCountEQ applies the EQ predicate on the "streak_count" field.
func StreakCountEQ(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldStreakCount, v))
}

// StreakCountNEQ applies the NEQ predicate on the "streak_count" field.
func StreakCountNEQ(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldStreakCount, v))
}

// StreakCountIn applies the In predicate on the "streak_count" field.
func StreakCountIn(vs ...int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldStreakCount, vs...))
}

// StreakCountNotIn applies the NotIn predicate on the "streak_count" field.
func StreakCountNotIn(vs ...int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldStreakCount, vs...))
}

// StreakCountGT applies the GT predicate on the "streak_count" field.
func StreakCountGT(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldStreakCount, v))
}

// StreakCountGTE applies the GTE predicate on the "streak_count" field.
func StreakCountGTE(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldStreakCount, v))
}

// StreakCountLT applies the LT predicate on the "streak_count" field.
func StreakCountLT(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldStreakCount, v))
}

// StreakCountLTE applies the LTE predicate on the "streak_count" field.
func StreakCountLTE(v int) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldStreakCount, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldScore, v))
}

// RechargeSnapshotEQ applies the EQ predicate on the "recharge_snapshot" field.
func RechargeSnapshotEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldRechargeSnapshot, v))
}

// RechargeSnapshotNEQ applies the NEQ predicate on the "recharge_snapshot" field.
func RechargeSnapshotNEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldRechargeSnapshot, v))
}

// RechargeSnapshotIn applies the In predicate on the "recharge_snapshot" field.
func RechargeSnapshotIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldRechargeSnapshot, vs...))
}

// RechargeSnapshotNotIn applies the NotIn predicate on the "recharge_snapshot" field.
func RechargeSnapshotNotIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldRechargeSnapshot, vs...))
}

// RechargeSnapshotGT applies the GT predicate on the "recharge_snapshot" field.
func RechargeSnapshotGT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldRechargeSnapshot, v))
}

// RechargeSnapshotGTE applies the GTE predicate on the "recharge_snapshot" field.
func RechargeSnapshotGTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldRechargeSnapshot, v))
}

// RechargeSnapshotLT applies the LT predicate on the "recharge_snapshot" field.
func RechargeSnapshotLT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldRechargeSnapshot, v))
}

// RechargeSnapshotLTE applies the LTE predicate on the "recharge_snapshot" field.
func RechargeSnapshotLTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldRechargeSnapshot, v))
}

// UsageSnapshotEQ applies the EQ predicate on the "usage_snapshot" field.
func UsageSnapshotEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldUsageSnapshot, v))
}

// UsageSnapshotNEQ applies the NEQ predicate on the "usage_snapshot" field.
func UsageSnapshotNEQ(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldUsageSnapshot, v))
}

// UsageSnapshotIn applies the In predicate on the "usage_snapshot" field.
func UsageSnapshotIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldUsageSnapshot, vs...))
}

// UsageSnapshotNotIn applies the NotIn predicate on the "usage_snapshot" field.
func UsageSnapshotNotIn(vs ...float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldUsageSnapshot, vs...))
}

// UsageSnapshotGT applies the GT predicate on the "usage_snapshot" field.
func UsageSnapshotGT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldUsageSnapshot, v))
}

// UsageSnapshotGTE applies the GTE predicate on the "usage_snapshot" field.
func UsageSnapshotGTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldUsageSnapshot, v))
}

// UsageSnapshotLT applies the LT predicate on the "usage_snapshot" field.
func UsageSnapshotLT(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldUsageSnapshot, v))
}

// UsageSnapshotLTE applies the LTE predicate on the "usage_snapshot" field.
func UsageSnapshotLTE(v float64) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldUsageSnapshot, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CheckInRecord) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CheckInRecord) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CheckInRecord) predicate.CheckInRecord {
	return predicate.CheckInRecord(sql.NotPredicates(p))
}
