// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrewardtier"
)

// CheckInRewardTierCreate is the builder for creating a CheckInRewardTier entity.
type CheckInRewardTierCreate struct {
	config
	mutation *CheckInRewardTierMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *CheckInRewardTierCreate) SetName(v string) *CheckInRewardTierCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CheckInRewardTierCreate) SetEnabled(v bool) *CheckInRewardTierCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableEnabled(v *bool) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetMatchType sets the "match_type" field.
func (_c *CheckInRewardTierCreate) SetMatchType(v string) *CheckInRewardTierCreate {
	_c.mutation.SetMatchType(v)
	return _c
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableMatchType(v *string) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetMatchType(*v)
	}
	return _c
}

// SetMatchThreshold sets the "match_threshold" field.
func (_c *CheckInRewardTierCreate) SetMatchThreshold(v float64) *CheckInRewardTierCreate {
	_c.mutation.SetMatchThreshold(v)
	return _c
}

// SetNillableMatchThreshold sets the "match_threshold" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableMatchThreshold(v *float64) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetMatchThreshold(*v)
	}
	return _c
}

// SetMinReward sets the "min_reward" field.
func (_c *CheckInRewardTierCreate) SetMinReward(v float64) *CheckInRewardTierCreate {
	_c.mutation.SetMinReward(v)
	return _c
}

// SetNillableMinReward sets the "min_reward" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableMinReward(v *float64) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetMinReward(*v)
	}
	return _c
}

// SetMaxReward sets the "max_reward" field.
func (_c *CheckInRewardTierCreate) SetMaxReward(v float64) *CheckInRewardTierCreate {
	_c.mutation.SetMaxReward(v)
	return _c
}

// SetNillableMaxReward sets the "max_reward" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableMaxReward(v *float64) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetMaxReward(*v)
	}
	return _c
}

// SetBaseCap sets the "base_cap" field.
func (_c *CheckInRewardTierCreate) SetBaseCap(v float64) *CheckInRewardTierCreate {
	_c.mutation.SetBaseCap(v)
	return _c
}

// SetNillableBaseCap sets the "base_cap" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableBaseCap(v *float64) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetBaseCap(*v)
	}
	return _c
}

// SetBetaMin sets the "beta_min" field.
func (_c *CheckInRewardTierCreate) SetBetaMin(v float64) *CheckInRewardTierCreate {
	_c.mutation.SetBetaMin(v)
	return _c
}

// SetNillableBetaMin sets the "beta_min" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableBetaMin(v *float64) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetBetaMin(*v)
	}
	return _c
}

// SetBetaMax sets the "beta_max" field.
func (_c *CheckInRewardTierCreate) SetBetaMax(v float64) *CheckInRewardTierCreate {
	_c.mutation.SetBetaMax(v)
	return _c
}

// SetNillableBetaMax sets the "beta_max" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableBetaMax(v *float64) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetBetaMax(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *CheckInRewardTierCreate) SetSortOrder(v int) *CheckInRewardTierCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableSortOrder(v *int) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CheckInRewardTierCreate) SetCreatedAt(v time.Time) *CheckInRewardTierCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableCreatedAt(v *time.Time) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CheckInRewardTierCreate) SetUpdatedAt(v time.Time) *CheckInRewardTierCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CheckInRewardTierCreate) SetNillableUpdatedAt(v *time.Time) *CheckInRewardTierCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CheckInRewardTierMutation object of the builder.
func (_c *CheckInRewardTierCreate) Mutation() *CheckInRewardTierMutation {
	return _c.mutation
}

// Save creates the CheckInRewardTier in the database.
func (_c *CheckInRewardTierCreate) Save(ctx context.Context) (*CheckInRewardTier, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheckInRewardTierCreate) SaveX(ctx context.Context) *CheckInRewardTier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckInRewardTierCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckInRewardTierCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheckInRewardTierCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := checkinrewardtier.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.MatchType(); !ok {
		v := checkinrewardtier.DefaultMatchType
		_c.mutation.SetMatchType(v)
	}
	if _, ok := _c.mutation.MatchThreshold(); !ok {
		v := checkinrewardtier.DefaultMatchThreshold
		_c.mutation.SetMatchThreshold(v)
	}
	if _, ok := _c.mutation.MinReward(); !ok {
		v := checkinrewardtier.DefaultMinReward
		_c.mutation.SetMinReward(v)
	}
	if _, ok := _c.mutation.MaxReward(); !ok {
		v := checkinrewardtier.DefaultMaxReward
		_c.mutation.SetMaxReward(v)
	}
	if _, ok := _c.mutation.BaseCap(); !ok {
		v := checkinrewardtier.DefaultBaseCap
		_c.mutation.SetBaseCap(v)
	}
	if _, ok := _c.mutation.BetaMin(); !ok {
		v := checkinrewardtier.DefaultBetaMin
		_c.mutation.SetBetaMin(v)
	}
	if _, ok := _c.mutation.BetaMax(); !ok {
		v := checkinrewardtier.DefaultBetaMax
		_c.mutation.SetBetaMax(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := checkinrewardtier.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := checkinrewardtier.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := checkinrewardtier.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheckInRewardTierCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CheckInRewardTier.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := checkinrewardtier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CheckInRewardTier.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CheckInRewardTier.enabled"`)}
	}
	if _, ok := _c.mutation.MatchType(); !ok {
		return &ValidationError{Name: "match_type", err: errors.New(`ent: missing required field "CheckInRewardTier.match_type"`)}
	}
	if v, ok := _c.mutation.MatchType(); ok {
		if err := checkinrewardtier.MatchTypeValidator(v); err != nil {
			return &ValidationError{Name: "match_type", err: fmt.Errorf(`ent: validator failed for field "CheckInRewardTier.match_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MatchThreshold(); !ok {
		return &ValidationError{Name: "match_threshold", err: errors.New(`ent: missing required field "CheckInRewardTier.match_threshold"`)}
	}
	if _, ok := _c.mutation.MinReward(); !ok {
		return &ValidationError{Name: "min_reward", err: errors.New(`ent: missing required field "CheckInRewardTier.min_reward"`)}
	}
	if _, ok := _c.mutation.MaxReward(); !ok {
		return &ValidationError{Name: "max_reward", err: errors.New(`ent: missing required field "CheckInRewardTier.max_reward"`)}
	}
	if _, ok := _c.mutation.BaseCap(); !ok {
		return &ValidationError{Name: "base_cap", err: errors.New(`ent: missing required field "CheckInRewardTier.base_cap"`)}
	}
	if _, ok := _c.mutation.BetaMin(); !ok {
		return &ValidationError{Name: "beta_min", err: errors.New(`ent: missing required field "CheckInRewardTier.beta_min"`)}
	}
	if _, ok := _c.mutation.BetaMax(); !ok {
		return &ValidationError{Name: "beta_max", err: errors.New(`ent: missing required field "CheckInRewardTier.beta_max"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "CheckInRewardTier.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CheckInRewardTier.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CheckInRewardTier.updated_at"`)}
	}
	return nil
}

func (_c *CheckInRewardTierCreate) sqlSave(ctx context.Context) (*CheckInRewardTier, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheckInRewardTierCreate) createSpec() (*CheckInRewardTier, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckInRewardTier{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checkinrewardtier.Table, sqlgraph.NewFieldSpec(checkinrewardtier.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(checkinrewardtier.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(checkinrewardtier.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.MatchType(); ok {
		_spec.SetField(checkinrewardtier.FieldMatchType, field.TypeString, value)
		_node.MatchType = value
	}
	if value, ok := _c.mutation.MatchThreshold(); ok {
		_spec.SetField(checkinrewardtier.FieldMatchThreshold, field.TypeFloat64, value)
		_node.MatchThreshold = value
	}
	if value, ok := _c.mutation.MinReward(); ok {
		_spec.SetField(checkinrewardtier.FieldMinReward, field.TypeFloat64, value)
		_node.MinReward = value
	}
	if value, ok := _c.mutation.MaxReward(); ok {
		_spec.SetField(checkinrewardtier.FieldMaxReward, field.TypeFloat64, value)
		_node.MaxReward = value
	}
	if value, ok := _c.mutation.BaseCap(); ok {
		_spec.SetField(checkinrewardtier.FieldBaseCap, field.TypeFloat64, value)
		_node.BaseCap = value
	}
	if value, ok := _c.mutation.BetaMin(); ok {
		_spec.SetField(checkinrewardtier.FieldBetaMin, field.TypeFloat64, value)
		_node.BetaMin = value
	}
	if value, ok := _c.mutation.BetaMax(); ok {
		_spec.SetField(checkinrewardtier.FieldBetaMax, field.TypeFloat64, value)
		_node.BetaMax = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(checkinrewardtier.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(checkinrewardtier.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(checkinrewardtier.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckInRewardTier.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckInRewardTierUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckInRewardTierCreate) OnConflict(opts ...sql.ConflictOption) *CheckInRewardTierUpsertOne {
	_c.conflict = opts
	return &CheckInRewardTierUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckInRewardTier.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckInRewardTierCreate) OnConflictColumns(columns ...string) *CheckInRewardTierUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckInRewardTierUpsertOne{
		create: _c,
	}
}

type (
	// CheckInRewardTierUpsertOne is the builder for "upsert"-ing
	//  one CheckInRewardTier node.
	CheckInRewardTierUpsertOne struct {
		create *CheckInRewardTierCreate
	}

	// CheckInRewardTierUpsert is the "OnConflict" setter.
	CheckInRewardTierUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *CheckInRewardTierUpsert) SetName(v string) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateName() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldName)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CheckInRewardTierUpsert) SetEnabled(v bool) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateEnabled() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldEnabled)
	return u
}

// SetMatchType sets the "match_type" field.
func (u *CheckInRewardTierUpsert) SetMatchType(v string) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldMatchType, v)
	return u
}

// UpdateMatchType sets the "match_type" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateMatchType() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldMatchType)
	return u
}

// SetMatchThreshold sets the "match_threshold" field.
func (u *CheckInRewardTierUpsert) SetMatchThreshold(v float64) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldMatchThreshold, v)
	return u
}

// UpdateMatchThreshold sets the "match_threshold" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateMatchThreshold() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldMatchThreshold)
	return u
}

// AddMatchThreshold adds v to the "match_threshold" field.
func (u *CheckInRewardTierUpsert) AddMatchThreshold(v float64) *CheckInRewardTierUpsert {
	u.Add(checkinrewardtier.FieldMatchThreshold, v)
	return u
}

// SetMinReward sets the "min_reward" field.
func (u *CheckInRewardTierUpsert) SetMinReward(v float64) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldMinReward, v)
	return u
}

// UpdateMinReward sets the "min_reward" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateMinReward() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldMinReward)
	return u
}

// AddMinReward adds v to the "min_reward" field.
func (u *CheckInRewardTierUpsert) AddMinReward(v float64) *CheckInRewardTierUpsert {
	u.Add(checkinrewardtier.FieldMinReward, v)
	return u
}

// SetMaxReward sets the "max_reward" field.
func (u *CheckInRewardTierUpsert) SetMaxReward(v float64) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldMaxReward, v)
	return u
}

// UpdateMaxReward sets the "max_reward" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateMaxReward() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldMaxReward)
	return u
}

// AddMaxReward adds v to the "max_reward" field.
func (u *CheckInRewardTierUpsert) AddMaxReward(v float64) *CheckInRewardTierUpsert {
	u.Add(checkinrewardtier.FieldMaxReward, v)
	return u
}

// SetBaseCap sets the "base_cap" field.
func (u *CheckInRewardTierUpsert) SetBaseCap(v float64) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldBaseCap, v)
	return u
}

// UpdateBaseCap sets the "base_cap" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateBaseCap() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldBaseCap)
	return u
}

// AddBaseCap adds v to the "base_cap" field.
func (u *CheckInRewardTierUpsert) AddBaseCap(v float64) *CheckInRewardTierUpsert {
	u.Add(checkinrewardtier.FieldBaseCap, v)
	return u
}

// SetBetaMin sets the "beta_min" field.
func (u *CheckInRewardTierUpsert) SetBetaMin(v float64) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldBetaMin, v)
	return u
}

// UpdateBetaMin sets the "beta_min" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateBetaMin() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldBetaMin)
	return u
}

// AddBetaMin adds v to the "beta_min" field.
func (u *CheckInRewardTierUpsert) AddBetaMin(v float64) *CheckInRewardTierUpsert {
	u.Add(checkinrewardtier.FieldBetaMin, v)
	return u
}

// SetBetaMax sets the "beta_max" field.
func (u *CheckInRewardTierUpsert) SetBetaMax(v float64) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldBetaMax, v)
	return u
}

// UpdateBetaMax sets the "beta_max" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateBetaMax() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldBetaMax)
	return u
}

// AddBetaMax adds v to the "beta_max" field.
func (u *CheckInRewardTierUpsert) AddBetaMax(v float64) *CheckInRewardTierUpsert {
	u.Add(checkinrewardtier.FieldBetaMax, v)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *CheckInRewardTierUpsert) SetSortOrder(v int) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateSortOrder() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CheckInRewardTierUpsert) AddSortOrder(v int) *CheckInRewardTierUpsert {
	u.Add(checkinrewardtier.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CheckInRewardTierUpsert) SetUpdatedAt(v time.Time) *CheckInRewardTierUpsert {
	u.Set(checkinrewardtier.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CheckInRewardTierUpsert) UpdateUpdatedAt() *CheckInRewardTierUpsert {
	u.SetExcluded(checkinrewardtier.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CheckInRewardTier.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckInRewardTierUpsertOne) UpdateNewValues() *CheckInRewardTierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(checkinrewardtier.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckInRewardTier.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CheckInRewardTierUpsertOne) Ignore() *CheckInRewardTierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckInRewardTierUpsertOne) DoNothing() *CheckInRewardTierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckInRewardTierCreate.OnConflict
// documentation for more info.
func (u *CheckInRewardTierUpsertOne) Update(set func(*CheckInRewardTierUpsert)) *CheckInRewardTierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckInRewardTierUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CheckInRewardTierUpsertOne) SetName(v string) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateName() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CheckInRewardTierUpsertOne) SetEnabled(v bool) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateEnabled() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateEnabled()
	})
}

// SetMatchType sets the "match_type" field.
func (u *CheckInRewardTierUpsertOne) SetMatchType(v string) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetMatchType(v)
	})
}

// UpdateMatchType sets the "match_type" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateMatchType() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateMatchType()
	})
}

// SetMatchThreshold sets the "match_threshold" field.
func (u *CheckInRewardTierUpsertOne) SetMatchThreshold(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetMatchThreshold(v)
	})
}

// AddMatchThreshold adds v to the "match_threshold" field.
func (u *CheckInRewardTierUpsertOne) AddMatchThreshold(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddMatchThreshold(v)
	})
}

// UpdateMatchThreshold sets the "match_threshold" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateMatchThreshold() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateMatchThreshold()
	})
}

// SetMinReward sets the "min_reward" field.
func (u *CheckInRewardTierUpsertOne) SetMinReward(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetMinReward(v)
	})
}

// AddMinReward adds v to the "min_reward" field.
func (u *CheckInRewardTierUpsertOne) AddMinReward(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddMinReward(v)
	})
}

// UpdateMinReward sets the "min_reward" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateMinReward() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateMinReward()
	})
}

// SetMaxReward sets the "max_reward" field.
func (u *CheckInRewardTierUpsertOne) SetMaxReward(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetMaxReward(v)
	})
}

// AddMaxReward adds v to the "max_reward" field.
func (u *CheckInRewardTierUpsertOne) AddMaxReward(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddMaxReward(v)
	})
}

// UpdateMaxReward sets the "max_reward" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateMaxReward() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateMaxReward()
	})
}

// SetBaseCap sets the "base_cap" field.
func (u *CheckInRewardTierUpsertOne) SetBaseCap(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetBaseCap(v)
	})
}

// AddBaseCap adds v to the "base_cap" field.
func (u *CheckInRewardTierUpsertOne) AddBaseCap(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddBaseCap(v)
	})
}

// UpdateBaseCap sets the "base_cap" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateBaseCap() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateBaseCap()
	})
}

// SetBetaMin sets the "beta_min" field.
func (u *CheckInRewardTierUpsertOne) SetBetaMin(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetBetaMin(v)
	})
}

// AddBetaMin adds v to the "beta_min" field.
func (u *CheckInRewardTierUpsertOne) AddBetaMin(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddBetaMin(v)
	})
}

// UpdateBetaMin sets the "beta_min" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateBetaMin() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateBetaMin()
	})
}

// SetBetaMax sets the "beta_max" field.
func (u *CheckInRewardTierUpsertOne) SetBetaMax(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetBetaMax(v)
	})
}

// AddBetaMax adds v to the "beta_max" field.
func (u *CheckInRewardTierUpsertOne) AddBetaMax(v float64) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddBetaMax(v)
	})
}

// UpdateBetaMax sets the "beta_max" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateBetaMax() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateBetaMax()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CheckInRewardTierUpsertOne) SetSortOrder(v int) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CheckInRewardTierUpsertOne) AddSortOrder(v int) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateSortOrder() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CheckInRewardTierUpsertOne) SetUpdatedAt(v time.Time) *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertOne) UpdateUpdatedAt() *CheckInRewardTierUpsertOne {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CheckInRewardTierUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckInRewardTierCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckInRewardTierUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CheckInRewardTierUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CheckInRewardTierUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CheckInRewardTierCreateBulk is the builder for creating many CheckInRewardTier entities in bulk.
type CheckInRewardTierCreateBulk struct {
	config
	err      error
	builders []*CheckInRewardTierCreate
	conflict []sql.ConflictOption
}

// Save creates the CheckInRewardTier entities in the database.
func (_c *CheckInRewardTierCreateBulk) Save(ctx context.Context) ([]*CheckInRewardTier, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CheckInRewardTier, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckInRewardTierMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheckInRewardTierCreateBulk) SaveX(ctx context.Context) []*CheckInRewardTier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckInRewardTierCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckInRewardTierCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckInRewardTier.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckInRewardTierUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckInRewardTierCreateBulk) OnConflict(opts ...sql.ConflictOption) *CheckInRewardTierUpsertBulk {
	_c.conflict = opts
	return &CheckInRewardTierUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckInRewardTier.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckInRewardTierCreateBulk) OnConflictColumns(columns ...string) *CheckInRewardTierUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckInRewardTierUpsertBulk{
		create: _c,
	}
}

// CheckInRewardTierUpsertBulk is the builder for "upsert"-ing
// a bulk of CheckInRewardTier nodes.
type CheckInRewardTierUpsertBulk struct {
	create *CheckInRewardTierCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CheckInRewardTier.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckInRewardTierUpsertBulk) UpdateNewValues() *CheckInRewardTierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(checkinrewardtier.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckInRewardTier.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CheckInRewardTierUpsertBulk) Ignore() *CheckInRewardTierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckInRewardTierUpsertBulk) DoNothing() *CheckInRewardTierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckInRewardTierCreateBulk.OnConflict
// documentation for more info.
func (u *CheckInRewardTierUpsertBulk) Update(set func(*CheckInRewardTierUpsert)) *CheckInRewardTierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckInRewardTierUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CheckInRewardTierUpsertBulk) SetName(v string) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateName() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CheckInRewardTierUpsertBulk) SetEnabled(v bool) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateEnabled() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateEnabled()
	})
}

// SetMatchType sets the "match_type" field.
func (u *CheckInRewardTierUpsertBulk) SetMatchType(v string) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetMatchType(v)
	})
}

// UpdateMatchType sets the "match_type" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateMatchType() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateMatchType()
	})
}

// SetMatchThreshold sets the "match_threshold" field.
func (u *CheckInRewardTierUpsertBulk) SetMatchThreshold(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetMatchThreshold(v)
	})
}

// AddMatchThreshold adds v to the "match_threshold" field.
func (u *CheckInRewardTierUpsertBulk) AddMatchThreshold(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddMatchThreshold(v)
	})
}

// UpdateMatchThreshold sets the "match_threshold" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateMatchThreshold() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateMatchThreshold()
	})
}

// SetMinReward sets the "min_reward" field.
func (u *CheckInRewardTierUpsertBulk) SetMinReward(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetMinReward(v)
	})
}

// AddMinReward adds v to the "min_reward" field.
func (u *CheckInRewardTierUpsertBulk) AddMinReward(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddMinReward(v)
	})
}

// UpdateMinReward sets the "min_reward" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateMinReward() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateMinReward()
	})
}

// SetMaxReward sets the "max_reward" field.
func (u *CheckInRewardTierUpsertBulk) SetMaxReward(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetMaxReward(v)
	})
}

// AddMaxReward adds v to the "max_reward" field.
func (u *CheckInRewardTierUpsertBulk) AddMaxReward(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddMaxReward(v)
	})
}

// UpdateMaxReward sets the "max_reward" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateMaxReward() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateMaxReward()
	})
}

// SetBaseCap sets the "base_cap" field.
func (u *CheckInRewardTierUpsertBulk) SetBaseCap(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetBaseCap(v)
	})
}

// AddBaseCap adds v to the "base_cap" field.
func (u *CheckInRewardTierUpsertBulk) AddBaseCap(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddBaseCap(v)
	})
}

// UpdateBaseCap sets the "base_cap" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateBaseCap() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateBaseCap()
	})
}

// SetBetaMin sets the "beta_min" field.
func (u *CheckInRewardTierUpsertBulk) SetBetaMin(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetBetaMin(v)
	})
}

// AddBetaMin adds v to the "beta_min" field.
func (u *CheckInRewardTierUpsertBulk) AddBetaMin(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddBetaMin(v)
	})
}

// UpdateBetaMin sets the "beta_min" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateBetaMin() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateBetaMin()
	})
}

// SetBetaMax sets the "beta_max" field.
func (u *CheckInRewardTierUpsertBulk) SetBetaMax(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetBetaMax(v)
	})
}

// AddBetaMax adds v to the "beta_max" field.
func (u *CheckInRewardTierUpsertBulk) AddBetaMax(v float64) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddBetaMax(v)
	})
}

// UpdateBetaMax sets the "beta_max" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateBetaMax() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateBetaMax()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CheckInRewardTierUpsertBulk) SetSortOrder(v int) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CheckInRewardTierUpsertBulk) AddSortOrder(v int) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateSortOrder() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CheckInRewardTierUpsertBulk) SetUpdatedAt(v time.Time) *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CheckInRewardTierUpsertBulk) UpdateUpdatedAt() *CheckInRewardTierUpsertBulk {
	return u.Update(func(s *CheckInRewardTierUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CheckInRewardTierUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CheckInRewardTierCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckInRewardTierCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckInRewardTierUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
