// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrewardtier"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CheckInRewardTierUpdate is the builder for updating CheckInRewardTier entities.
type CheckInRewardTierUpdate struct {
	config
	hooks    []Hook
	mutation *CheckInRewardTierMutation
}

// Where appends a list predicates to the CheckInRewardTierUpdate builder.
func (_u *CheckInRewardTierUpdate) Where(ps ...predicate.CheckInRewardTier) *CheckInRewardTierUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CheckInRewardTierUpdate) SetName(v string) *CheckInRewardTierUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableName(v *string) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CheckInRewardTierUpdate) SetEnabled(v bool) *CheckInRewardTierUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableEnabled(v *bool) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *CheckInRewardTierUpdate) SetMatchType(v string) *CheckInRewardTierUpdate {
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableMatchType(v *string) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// SetMatchThreshold sets the "match_threshold" field.
func (_u *CheckInRewardTierUpdate) SetMatchThreshold(v float64) *CheckInRewardTierUpdate {
	_u.mutation.ResetMatchThreshold()
	_u.mutation.SetMatchThreshold(v)
	return _u
}

// SetNillableMatchThreshold sets the "match_threshold" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableMatchThreshold(v *float64) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetMatchThreshold(*v)
	}
	return _u
}

// AddMatchThreshold adds value to the "match_threshold" field.
func (_u *CheckInRewardTierUpdate) AddMatchThreshold(v float64) *CheckInRewardTierUpdate {
	_u.mutation.AddMatchThreshold(v)
	return _u
}

// SetMinReward sets the "min_reward" field.
func (_u *CheckInRewardTierUpdate) SetMinReward(v float64) *CheckInRewardTierUpdate {
	_u.mutation.ResetMinReward()
	_u.mutation.SetMinReward(v)
	return _u
}

// SetNillableMinReward sets the "min_reward" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableMinReward(v *float64) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetMinReward(*v)
	}
	return _u
}

// AddMinReward adds value to the "min_reward" field.
func (_u *CheckInRewardTierUpdate) AddMinReward(v float64) *CheckInRewardTierUpdate {
	_u.mutation.AddMinReward(v)
	return _u
}

// SetMaxReward sets the "max_reward" field.
func (_u *CheckInRewardTierUpdate) SetMaxReward(v float64) *CheckInRewardTierUpdate {
	_u.mutation.ResetMaxReward()
	_u.mutation.SetMaxReward(v)
	return _u
}

// SetNillableMaxReward sets the "max_reward" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableMaxReward(v *float64) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetMaxReward(*v)
	}
	return _u
}

// AddMaxReward adds value to the "max_reward" field.
func (_u *CheckInRewardTierUpdate) AddMaxReward(v float64) *CheckInRewardTierUpdate {
	_u.mutation.AddMaxReward(v)
	return _u
}

// SetBaseCap sets the "base_cap" field.
func (_u *CheckInRewardTierUpdate) SetBaseCap(v float64) *CheckInRewardTierUpdate {
	_u.mutation.ResetBaseCap()
	_u.mutation.SetBaseCap(v)
	return _u
}

// SetNillableBaseCap sets the "base_cap" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableBaseCap(v *float64) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetBaseCap(*v)
	}
	return _u
}

// AddBaseCap adds value to the "base_cap" field.
func (_u *CheckInRewardTierUpdate) AddBaseCap(v float64) *CheckInRewardTierUpdate {
	_u.mutation.AddBaseCap(v)
	return _u
}

// SetBetaMin sets the "beta_min" field.
func (_u *CheckInRewardTierUpdate) SetBetaMin(v float64) *CheckInRewardTierUpdate {
	_u.mutation.ResetBetaMin()
	_u.mutation.SetBetaMin(v)
	return _u
}

// SetNillableBetaMin sets the "beta_min" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableBetaMin(v *float64) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetBetaMin(*v)
	}
	return _u
}

// AddBetaMin adds value to the "beta_min" field.
func (_u *CheckInRewardTierUpdate) AddBetaMin(v float64) *CheckInRewardTierUpdate {
	_u.mutation.AddBetaMin(v)
	return _u
}

// SetBetaMax sets the "beta_max" field.
func (_u *CheckInRewardTierUpdate) SetBetaMax(v float64) *CheckInRewardTierUpdate {
	_u.mutation.ResetBetaMax()
	_u.mutation.SetBetaMax(v)
	return _u
}

// SetNillableBetaMax sets the "beta_max" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableBetaMax(v *float64) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetBetaMax(*v)
	}
	return _u
}

// AddBetaMax adds value to the "beta_max" field.
func (_u *CheckInRewardTierUpdate) AddBetaMax(v float64) *CheckInRewardTierUpdate {
	_u.mutation.AddBetaMax(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CheckInRewardTierUpdate) SetSortOrder(v int) *CheckInRewardTierUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CheckInRewardTierUpdate) SetNillableSortOrder(v *int) *CheckInRewardTierUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CheckInRewardTierUpdate) AddSortOrder(v int) *CheckInRewardTierUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CheckInRewardTierUpdate) SetUpdatedAt(v time.Time) *CheckInRewardTierUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CheckInRewardTierMutation object of the builder.
func (_u *CheckInRewardTierUpdate) Mutation() *CheckInRewardTierMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckInRewardTierUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckInRewardTierUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckInRewardTierUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckInRewardTierUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CheckInRewardTierUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := checkinrewardtier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckInRewardTierUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := checkinrewardtier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CheckInRewardTier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchType(); ok {
		if err := checkinrewardtier.MatchTypeValidator(v); err != nil {
			return &ValidationError{Name: "match_type", err: fmt.Errorf(`ent: validator failed for field "CheckInRewardTier.match_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CheckInRewardTierUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrewardtier.Table, checkinrewardtier.Columns, sqlgraph.NewFieldSpec(checkinrewardtier.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(checkinrewardtier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(checkinrewardtier.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(checkinrewardtier.FieldMatchType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchThreshold(); ok {
		_spec.SetField(checkinrewardtier.FieldMatchThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMatchThreshold(); ok {
		_spec.AddField(checkinrewardtier.FieldMatchThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinReward(); ok {
		_spec.SetField(checkinrewardtier.FieldMinReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinReward(); ok {
		_spec.AddField(checkinrewardtier.FieldMinReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxReward(); ok {
		_spec.SetField(checkinrewardtier.FieldMaxReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxReward(); ok {
		_spec.AddField(checkinrewardtier.FieldMaxReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BaseCap(); ok {
		_spec.SetField(checkinrewardtier.FieldBaseCap, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseCap(); ok {
		_spec.AddField(checkinrewardtier.FieldBaseCap, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BetaMin(); ok {
		_spec.SetField(checkinrewardtier.FieldBetaMin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBetaMin(); ok {
		_spec.AddField(checkinrewardtier.FieldBetaMin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BetaMax(); ok {
		_spec.SetField(checkinrewardtier.FieldBetaMax, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBetaMax(); ok {
		_spec.AddField(checkinrewardtier.FieldBetaMax, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(checkinrewardtier.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(checkinrewardtier.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(checkinrewardtier.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrewardtier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckInRewardTierUpdateOne is the builder for updating a single CheckInRewardTier entity.
type CheckInRewardTierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckInRewardTierMutation
}

// SetName sets the "name" field.
func (_u *CheckInRewardTierUpdateOne) SetName(v string) *CheckInRewardTierUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableName(v *string) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CheckInRewardTierUpdateOne) SetEnabled(v bool) *CheckInRewardTierUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableEnabled(v *bool) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *CheckInRewardTierUpdateOne) SetMatchType(v string) *CheckInRewardTierUpdateOne {
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableMatchType(v *string) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// SetMatchThreshold sets the "match_threshold" field.
func (_u *CheckInRewardTierUpdateOne) SetMatchThreshold(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.ResetMatchThreshold()
	_u.mutation.SetMatchThreshold(v)
	return _u
}

// SetNillableMatchThreshold sets the "match_threshold" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableMatchThreshold(v *float64) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetMatchThreshold(*v)
	}
	return _u
}

// AddMatchThreshold adds value to the "match_threshold" field.
func (_u *CheckInRewardTierUpdateOne) AddMatchThreshold(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.AddMatchThreshold(v)
	return _u
}

// SetMinReward sets the "min_reward" field.
func (_u *CheckInRewardTierUpdateOne) SetMinReward(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.ResetMinReward()
	_u.mutation.SetMinReward(v)
	return _u
}

// SetNillableMinReward sets the "min_reward" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableMinReward(v *float64) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetMinReward(*v)
	}
	return _u
}

// AddMinReward adds value to the "min_reward" field.
func (_u *CheckInRewardTierUpdateOne) AddMinReward(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.AddMinReward(v)
	return _u
}

// SetMaxReward sets the "max_reward" field.
func (_u *CheckInRewardTierUpdateOne) SetMaxReward(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.ResetMaxReward()
	_u.mutation.SetMaxReward(v)
	return _u
}

// SetNillableMaxReward sets the "max_reward" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableMaxReward(v *float64) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetMaxReward(*v)
	}
	return _u
}

// AddMaxReward adds value to the "max_reward" field.
func (_u *CheckInRewardTierUpdateOne) AddMaxReward(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.AddMaxReward(v)
	return _u
}

// SetBaseCap sets the "base_cap" field.
func (_u *CheckInRewardTierUpdateOne) SetBaseCap(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.ResetBaseCap()
	_u.mutation.SetBaseCap(v)
	return _u
}

// SetNillableBaseCap sets the "base_cap" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableBaseCap(v *float64) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetBaseCap(*v)
	}
	return _u
}

// AddBaseCap adds value to the "base_cap" field.
func (_u *CheckInRewardTierUpdateOne) AddBaseCap(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.AddBaseCap(v)
	return _u
}

// SetBetaMin sets the "beta_min" field.
func (_u *CheckInRewardTierUpdateOne) SetBetaMin(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.ResetBetaMin()
	_u.mutation.SetBetaMin(v)
	return _u
}

// SetNillableBetaMin sets the "beta_min" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableBetaMin(v *float64) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetBetaMin(*v)
	}
	return _u
}

// AddBetaMin adds value to the "beta_min" field.
func (_u *CheckInRewardTierUpdateOne) AddBetaMin(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.AddBetaMin(v)
	return _u
}

// SetBetaMax sets the "beta_max" field.
func (_u *CheckInRewardTierUpdateOne) SetBetaMax(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.ResetBetaMax()
	_u.mutation.SetBetaMax(v)
	return _u
}

// SetNillableBetaMax sets the "beta_max" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableBetaMax(v *float64) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetBetaMax(*v)
	}
	return _u
}

// AddBetaMax adds value to the "beta_max" field.
func (_u *CheckInRewardTierUpdateOne) AddBetaMax(v float64) *CheckInRewardTierUpdateOne {
	_u.mutation.AddBetaMax(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CheckInRewardTierUpdateOne) SetSortOrder(v int) *CheckInRewardTierUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CheckInRewardTierUpdateOne) SetNillableSortOrder(v *int) *CheckInRewardTierUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CheckInRewardTierUpdateOne) AddSortOrder(v int) *CheckInRewardTierUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CheckInRewardTierUpdateOne) SetUpdatedAt(v time.Time) *CheckInRewardTierUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CheckInRewardTierMutation object of the builder.
func (_u *CheckInRewardTierUpdateOne) Mutation() *CheckInRewardTierMutation {
	return _u.mutation
}

// Where appends a list predicates to the CheckInRewardTierUpdate builder.
func (_u *CheckInRewardTierUpdateOne) Where(ps ...predicate.CheckInRewardTier) *CheckInRewardTierUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckInRewardTierUpdateOne) Select(field string, fields ...string) *CheckInRewardTierUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckInRewardTier entity.
func (_u *CheckInRewardTierUpdateOne) Save(ctx context.Context) (*CheckInRewardTier, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckInRewardTierUpdateOne) SaveX(ctx context.Context) *CheckInRewardTier {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckInRewardTierUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckInRewardTierUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CheckInRewardTierUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := checkinrewardtier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckInRewardTierUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := checkinrewardtier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CheckInRewardTier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchType(); ok {
		if err := checkinrewardtier.MatchTypeValidator(v); err != nil {
			return &ValidationError{Name: "match_type", err: fmt.Errorf(`ent: validator failed for field "CheckInRewardTier.match_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CheckInRewardTierUpdateOne) sqlSave(ctx context.Context) (_node *CheckInRewardTier, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrewardtier.Table, checkinrewardtier.Columns, sqlgraph.NewFieldSpec(checkinrewardtier.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckInRewardTier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkinrewardtier.FieldID)
		for _, f := range fields {
			if !checkinrewardtier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkinrewardtier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(checkinrewardtier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(checkinrewardtier.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(checkinrewardtier.FieldMatchType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchThreshold(); ok {
		_spec.SetField(checkinrewardtier.FieldMatchThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMatchThreshold(); ok {
		_spec.AddField(checkinrewardtier.FieldMatchThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinReward(); ok {
		_spec.SetField(checkinrewardtier.FieldMinReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinReward(); ok {
		_spec.AddField(checkinrewardtier.FieldMinReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxReward(); ok {
		_spec.SetField(checkinrewardtier.FieldMaxReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxReward(); ok {
		_spec.AddField(checkinrewardtier.FieldMaxReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BaseCap(); ok {
		_spec.SetField(checkinrewardtier.FieldBaseCap, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseCap(); ok {
		_spec.AddField(checkinrewardtier.FieldBaseCap, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BetaMin(); ok {
		_spec.SetField(checkinrewardtier.FieldBetaMin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBetaMin(); ok {
		_spec.AddField(checkinrewardtier.FieldBetaMin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BetaMax(); ok {
		_spec.SetField(checkinrewardtier.FieldBetaMax, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBetaMax(); ok {
		_spec.AddField(checkinrewardtier.FieldBetaMax, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(checkinrewardtier.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(checkinrewardtier.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(checkinrewardtier.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CheckInRewardTier{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrewardtier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
