// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
)

// CheckInRecord is the model entity for the CheckInRecord schema.
type CheckInRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CheckInDate holds the value of the "check_in_date" field.
	CheckInDate time.Time `json:"check_in_date,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// StreakCount holds the value of the "streak_count" field.
	StreakCount int `json:"streak_count,omitempty"`
	// Score holds the value of the "score" field.
	Score float64 `json:"score,omitempty"`
	// RechargeSnapshot holds the value of the "recharge_snapshot" field.
	RechargeSnapshot float64 `json:"recharge_snapshot,omitempty"`
	// UsageSnapshot holds the value of the "usage_snapshot" field.
	UsageSnapshot float64 `json:"usage_snapshot,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckInRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkinrecord.FieldRewardAmount, checkinrecord.FieldScore, checkinrecord.FieldRechargeSnapshot, checkinrecord.FieldUsageSnapshot:
			values[i] = new(sql.NullFloat64)
		case checkinrecord.FieldID, checkinrecord.FieldUserID, checkinrecord.FieldStreakCount:
			values[i] = new(sql.NullInt64)
		case checkinrecord.FieldCheckInDate, checkinrecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckInRecord fields.
func (_m *CheckInRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkinrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case checkinrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case checkinrecord.FieldCheckInDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field check_in_date", values[i])
			} else if value.Valid {
				_m.CheckInDate = value.Time
			}
		case checkinrecord.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case checkinrecord.FieldStreakCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field streak_count", values[i])
			} else if value.Valid {
				_m.StreakCount = int(value.Int64)
			}
		case checkinrecord.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = value.Float64
			}
		case checkinrecord.FieldRechargeSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_snapshot", values[i])
			} else if value.Valid {
				_m.RechargeSnapshot = value.Float64
			}
		case checkinrecord.FieldUsageSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_snapshot", values[i])
			} else if value.Valid {
				_m.UsageSnapshot = value.Float64
			}
		case checkinrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckInRecord.
// This includes values selected through modifiers, order, etc.
func (_m *CheckInRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CheckInRecord.
// Note that you need to call CheckInRecord.Unwrap() before calling this method if this CheckInRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CheckInRecord) Update() *CheckInRecordUpdateOne {
	return NewCheckInRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CheckInRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CheckInRecord) Unwrap() *CheckInRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckInRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CheckInRecord) String() string {
	var builder strings.Builder
	builder.WriteString("CheckInRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("check_in_date=")
	builder.WriteString(_m.CheckInDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	builder.WriteString("streak_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.StreakCount))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("recharge_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.RechargeSnapshot))
	builder.WriteString(", ")
	builder.WriteString("usage_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageSnapshot))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CheckInRecords is a parsable slice of CheckInRecord.
type CheckInRecords []*CheckInRecord
