// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/checkinrewardtier"
)

// CheckInRewardTier is the model entity for the CheckInRewardTier schema.
type CheckInRewardTier struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 分层名称
	Name string `json:"name,omitempty"`
	// 是否启用
	Enabled bool `json:"enabled,omitempty"`
	// 匹配维度: recharge | score
	MatchType string `json:"match_type,omitempty"`
	// 匹配阈值（对应维度 >= 该值时命中）
	MatchThreshold float64 `json:"match_threshold,omitempty"`
	// 该分层单次最小奖励
	MinReward float64 `json:"min_reward,omitempty"`
	// 该分层单次最大奖励（会被全局上限二次夹紧）
	MaxReward float64 `json:"max_reward,omitempty"`
	// 该分层奖励区间基础上限
	BaseCap float64 `json:"base_cap,omitempty"`
	// 幂律分布 beta 下界
	BetaMin float64 `json:"beta_min,omitempty"`
	// 幂律分布 beta 上界
	BetaMax float64 `json:"beta_max,omitempty"`
	// 排序序号（越大越优先，用于同阈值 tie-break）
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckInRewardTier) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkinrewardtier.FieldEnabled:
			values[i] = new(sql.NullBool)
		case checkinrewardtier.FieldMatchThreshold, checkinrewardtier.FieldMinReward, checkinrewardtier.FieldMaxReward, checkinrewardtier.FieldBaseCap, checkinrewardtier.FieldBetaMin, checkinrewardtier.FieldBetaMax:
			values[i] = new(sql.NullFloat64)
		case checkinrewardtier.FieldID, checkinrewardtier.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case checkinrewardtier.FieldName, checkinrewardtier.FieldMatchType:
			values[i] = new(sql.NullString)
		case checkinrewardtier.FieldCreatedAt, checkinrewardtier.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckInRewardTier fields.
func (_m *CheckInRewardTier) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkinrewardtier.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case checkinrewardtier.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case checkinrewardtier.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case checkinrewardtier.FieldMatchType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_type", values[i])
			} else if value.Valid {
				_m.MatchType = value.String
			}
		case checkinrewardtier.FieldMatchThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field match_threshold", values[i])
			} else if value.Valid {
				_m.MatchThreshold = value.Float64
			}
		case checkinrewardtier.FieldMinReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field min_reward", values[i])
			} else if value.Valid {
				_m.MinReward = value.Float64
			}
		case checkinrewardtier.FieldMaxReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field max_reward", values[i])
			} else if value.Valid {
				_m.MaxReward = value.Float64
			}
		case checkinrewardtier.FieldBaseCap:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_cap", values[i])
			} else if value.Valid {
				_m.BaseCap = value.Float64
			}
		case checkinrewardtier.FieldBetaMin:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field beta_min", values[i])
			} else if value.Valid {
				_m.BetaMin = value.Float64
			}
		case checkinrewardtier.FieldBetaMax:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field beta_max", values[i])
			} else if value.Valid {
				_m.BetaMax = value.Float64
			}
		case checkinrewardtier.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case checkinrewardtier.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case checkinrewardtier.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckInRewardTier.
// This includes values selected through modifiers, order, etc.
func (_m *CheckInRewardTier) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CheckInRewardTier.
// Note that you need to call CheckInRewardTier.Unwrap() before calling this method if this CheckInRewardTier
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CheckInRewardTier) Update() *CheckInRewardTierUpdateOne {
	return NewCheckInRewardTierClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CheckInRewardTier entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CheckInRewardTier) Unwrap() *CheckInRewardTier {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckInRewardTier is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CheckInRewardTier) String() string {
	var builder strings.Builder
	builder.WriteString("CheckInRewardTier(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("match_type=")
	builder.WriteString(_m.MatchType)
	builder.WriteString(", ")
	builder.WriteString("match_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.MatchThreshold))
	builder.WriteString(", ")
	builder.WriteString("min_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinReward))
	builder.WriteString(", ")
	builder.WriteString("max_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxReward))
	builder.WriteString(", ")
	builder.WriteString("base_cap=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseCap))
	builder.WriteString(", ")
	builder.WriteString("beta_min=")
	builder.WriteString(fmt.Sprintf("%v", _m.BetaMin))
	builder.WriteString(", ")
	builder.WriteString("beta_max=")
	builder.WriteString(fmt.Sprintf("%v", _m.BetaMax))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CheckInRewardTiers is a parsable slice of CheckInRewardTier.
type CheckInRewardTiers []*CheckInRewardTier
