// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrewardtier"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CheckInRewardTierDelete is the builder for deleting a CheckInRewardTier entity.
type CheckInRewardTierDelete struct {
	config
	hooks    []Hook
	mutation *CheckInRewardTierMutation
}

// Where appends a list predicates to the CheckInRewardTierDelete builder.
func (_d *CheckInRewardTierDelete) Where(ps ...predicate.CheckInRewardTier) *CheckInRewardTierDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CheckInRewardTierDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CheckInRewardTierDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CheckInRewardTierDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(checkinrewardtier.Table, sqlgraph.NewFieldSpec(checkinrewardtier.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CheckInRewardTierDeleteOne is the builder for deleting a single CheckInRewardTier entity.
type CheckInRewardTierDeleteOne struct {
	_d *CheckInRewardTierDelete
}

// Where appends a list predicates to the CheckInRewardTierDelete builder.
func (_d *CheckInRewardTierDeleteOne) Where(ps ...predicate.CheckInRewardTier) *CheckInRewardTierDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CheckInRewardTierDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{checkinrewardtier.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CheckInRewardTierDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
