// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CheckInRecordUpdate is the builder for updating CheckInRecord entities.
type CheckInRecordUpdate struct {
	config
	hooks    []Hook
	mutation *CheckInRecordMutation
}

// Where appends a list predicates to the CheckInRecordUpdate builder.
func (_u *CheckInRecordUpdate) Where(ps ...predicate.CheckInRecord) *CheckInRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CheckInRecordUpdate) SetUserID(v int64) *CheckInRecordUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableUserID(v *int64) *CheckInRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CheckInRecordUpdate) AddUserID(v int64) *CheckInRecordUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCheckInDate sets the "check_in_date" field.
func (_u *CheckInRecordUpdate) SetCheckInDate(v time.Time) *CheckInRecordUpdate {
	_u.mutation.SetCheckInDate(v)
	return _u
}

// SetNillableCheckInDate sets the "check_in_date" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableCheckInDate(v *time.Time) *CheckInRecordUpdate {
	if v != nil {
		_u.SetCheckInDate(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *CheckInRecordUpdate) SetRewardAmount(v float64) *CheckInRecordUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableRewardAmount(v *float64) *CheckInRecordUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *CheckInRecordUpdate) AddRewardAmount(v float64) *CheckInRecordUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetStreakCount sets the "streak_count" field.
func (_u *CheckInRecordUpdate) SetStreakCount(v int) *CheckInRecordUpdate {
	_u.mutation.ResetStreakCount()
	_u.mutation.SetStreakCount(v)
	return _u
}

// SetNillableStreakCount sets the "streak_count" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableStreakCount(v *int) *CheckInRecordUpdate {
	if v != nil {
		_u.SetStreakCount(*v)
	}
	return _u
}

// AddStreakCount adds value to the "streak_count" field.
func (_u *CheckInRecordUpdate) AddStreakCount(v int) *CheckInRecordUpdate {
	_u.mutation.AddStreakCount(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *CheckInRecordUpdate) SetScore(v float64) *CheckInRecordUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableScore(v *float64) *CheckInRecordUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *CheckInRecordUpdate) AddScore(v float64) *CheckInRecordUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetRechargeSnapshot sets the "recharge_snapshot" field.
func (_u *CheckInRecordUpdate) SetRechargeSnapshot(v float64) *CheckInRecordUpdate {
	_u.mutation.ResetRechargeSnapshot()
	_u.mutation.SetRechargeSnapshot(v)
	return _u
}

// SetNillableRechargeSnapshot sets the "recharge_snapshot" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableRechargeSnapshot(v *float64) *CheckInRecordUpdate {
	if v != nil {
		_u.SetRechargeSnapshot(*v)
	}
	return _u
}

// AddRechargeSnapshot adds value to the "recharge_snapshot" field.
func (_u *CheckInRecordUpdate) AddRechargeSnapshot(v float64) *CheckInRecordUpdate {
	_u.mutation.AddRechargeSnapshot(v)
	return _u
}

// SetUsageSnapshot sets the "usage_snapshot" field.
func (_u *CheckInRecordUpdate) SetUsageSnapshot(v float64) *CheckInRecordUpdate {
	_u.mutation.ResetUsageSnapshot()
	_u.mutation.SetUsageSnapshot(v)
	return _u
}

// SetNillableUsageSnapshot sets the "usage_snapshot" field if the given value is not nil.
func (_u *CheckInRecordUpdate) SetNillableUsageSnapshot(v *float64) *CheckInRecordUpdate {
	if v != nil {
		_u.SetUsageSnapshot(*v)
	}
	return _u
}

// AddUsageSnapshot adds value to the "usage_snapshot" field.
func (_u *CheckInRecordUpdate) AddUsageSnapshot(v float64) *CheckInRecordUpdate {
	_u.mutation.AddUsageSnapshot(v)
	return _u
}

// Mutation returns the CheckInRecordMutation object of the builder.
func (_u *CheckInRecordUpdate) Mutation() *CheckInRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckInRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckInRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckInRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckInRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CheckInRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(checkinrecord.Table, checkinrecord.Columns, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(checkinrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(checkinrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CheckInDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckInDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(checkinrecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(checkinrecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakCount(); ok {
		_spec.SetField(checkinrecord.FieldStreakCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakCount(); ok {
		_spec.AddField(checkinrecord.FieldStreakCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(checkinrecord.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(checkinrecord.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RechargeSnapshot(); ok {
		_spec.SetField(checkinrecord.FieldRechargeSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeSnapshot(); ok {
		_spec.AddField(checkinrecord.FieldRechargeSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsageSnapshot(); ok {
		_spec.SetField(checkinrecord.FieldUsageSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsageSnapshot(); ok {
		_spec.AddField(checkinrecord.FieldUsageSnapshot, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckInRecordUpdateOne is the builder for updating a single CheckInRecord entity.
type CheckInRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckInRecordMutation
}

// SetUserID sets the "user_id" field.
func (_u *CheckInRecordUpdateOne) SetUserID(v int64) *CheckInRecordUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableUserID(v *int64) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CheckInRecordUpdateOne) AddUserID(v int64) *CheckInRecordUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetCheckInDate sets the "check_in_date" field.
func (_u *CheckInRecordUpdateOne) SetCheckInDate(v time.Time) *CheckInRecordUpdateOne {
	_u.mutation.SetCheckInDate(v)
	return _u
}

// SetNillableCheckInDate sets the "check_in_date" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableCheckInDate(v *time.Time) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetCheckInDate(*v)
	}
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *CheckInRecordUpdateOne) SetRewardAmount(v float64) *CheckInRecordUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableRewardAmount(v *float64) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *CheckInRecordUpdateOne) AddRewardAmount(v float64) *CheckInRecordUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetStreakCount sets the "streak_count" field.
func (_u *CheckInRecordUpdateOne) SetStreakCount(v int) *CheckInRecordUpdateOne {
	_u.mutation.ResetStreakCount()
	_u.mutation.SetStreakCount(v)
	return _u
}

// SetNillableStreakCount sets the "streak_count" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableStreakCount(v *int) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetStreakCount(*v)
	}
	return _u
}

// AddStreakCount adds value to the "streak_count" field.
func (_u *CheckInRecordUpdateOne) AddStreakCount(v int) *CheckInRecordUpdateOne {
	_u.mutation.AddStreakCount(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *CheckInRecordUpdateOne) SetScore(v float64) *CheckInRecordUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableScore(v *float64) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *CheckInRecordUpdateOne) AddScore(v float64) *CheckInRecordUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetRechargeSnapshot sets the "recharge_snapshot" field.
func (_u *CheckInRecordUpdateOne) SetRechargeSnapshot(v float64) *CheckInRecordUpdateOne {
	_u.mutation.ResetRechargeSnapshot()
	_u.mutation.SetRechargeSnapshot(v)
	return _u
}

// SetNillableRechargeSnapshot sets the "recharge_snapshot" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableRechargeSnapshot(v *float64) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetRechargeSnapshot(*v)
	}
	return _u
}

// AddRechargeSnapshot adds value to the "recharge_snapshot" field.
func (_u *CheckInRecordUpdateOne) AddRechargeSnapshot(v float64) *CheckInRecordUpdateOne {
	_u.mutation.AddRechargeSnapshot(v)
	return _u
}

// SetUsageSnapshot sets the "usage_snapshot" field.
func (_u *CheckInRecordUpdateOne) SetUsageSnapshot(v float64) *CheckInRecordUpdateOne {
	_u.mutation.ResetUsageSnapshot()
	_u.mutation.SetUsageSnapshot(v)
	return _u
}

// SetNillableUsageSnapshot sets the "usage_snapshot" field if the given value is not nil.
func (_u *CheckInRecordUpdateOne) SetNillableUsageSnapshot(v *float64) *CheckInRecordUpdateOne {
	if v != nil {
		_u.SetUsageSnapshot(*v)
	}
	return _u
}

// AddUsageSnapshot adds value to the "usage_snapshot" field.
func (_u *CheckInRecordUpdateOne) AddUsageSnapshot(v float64) *CheckInRecordUpdateOne {
	_u.mutation.AddUsageSnapshot(v)
	return _u
}

// Mutation returns the CheckInRecordMutation object of the builder.
func (_u *CheckInRecordUpdateOne) Mutation() *CheckInRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the CheckInRecordUpdate builder.
func (_u *CheckInRecordUpdateOne) Where(ps ...predicate.CheckInRecord) *CheckInRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckInRecordUpdateOne) Select(field string, fields ...string) *CheckInRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckInRecord entity.
func (_u *CheckInRecordUpdateOne) Save(ctx context.Context) (*CheckInRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckInRecordUpdateOne) SaveX(ctx context.Context) *CheckInRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckInRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckInRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CheckInRecordUpdateOne) sqlSave(ctx context.Context) (_node *CheckInRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(checkinrecord.Table, checkinrecord.Columns, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckInRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkinrecord.FieldID)
		for _, f := range fields {
			if !checkinrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkinrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(checkinrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(checkinrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CheckInDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckInDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(checkinrecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(checkinrecord.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakCount(); ok {
		_spec.SetField(checkinrecord.FieldStreakCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakCount(); ok {
		_spec.AddField(checkinrecord.FieldStreakCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(checkinrecord.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(checkinrecord.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RechargeSnapshot(); ok {
		_spec.SetField(checkinrecord.FieldRechargeSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeSnapshot(); ok {
		_spec.AddField(checkinrecord.FieldRechargeSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsageSnapshot(); ok {
		_spec.SetField(checkinrecord.FieldUsageSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsageSnapshot(); ok {
		_spec.AddField(checkinrecord.FieldUsageSnapshot, field.TypeFloat64, value)
	}
	_node = &CheckInRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
