// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinrecord"
)

// CheckInRecordCreate is the builder for creating a CheckInRecord entity.
type CheckInRecordCreate struct {
	config
	mutation *CheckInRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CheckInRecordCreate) SetUserID(v int64) *CheckInRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCheckInDate sets the "check_in_date" field.
func (_c *CheckInRecordCreate) SetCheckInDate(v time.Time) *CheckInRecordCreate {
	_c.mutation.SetCheckInDate(v)
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *CheckInRecordCreate) SetRewardAmount(v float64) *CheckInRecordCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_c *CheckInRecordCreate) SetNillableRewardAmount(v *float64) *CheckInRecordCreate {
	if v != nil {
		_c.SetRewardAmount(*v)
	}
	return _c
}

// SetStreakCount sets the "streak_count" field.
func (_c *CheckInRecordCreate) SetStreakCount(v int) *CheckInRecordCreate {
	_c.mutation.SetStreakCount(v)
	return _c
}

// SetNillableStreakCount sets the "streak_count" field if the given value is not nil.
func (_c *CheckInRecordCreate) SetNillableStreakCount(v *int) *CheckInRecordCreate {
	if v != nil {
		_c.SetStreakCount(*v)
	}
	return _c
}

// SetScore sets the "score" field.
func (_c *CheckInRecordCreate) SetScore(v float64) *CheckInRecordCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *CheckInRecordCreate) SetNillableScore(v *float64) *CheckInRecordCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetRechargeSnapshot sets the "recharge_snapshot" field.
func (_c *CheckInRecordCreate) SetRechargeSnapshot(v float64) *CheckInRecordCreate {
	_c.mutation.SetRechargeSnapshot(v)
	return _c
}

// SetNillableRechargeSnapshot sets the "recharge_snapshot" field if the given value is not nil.
func (_c *CheckInRecordCreate) SetNillableRechargeSnapshot(v *float64) *CheckInRecordCreate {
	if v != nil {
		_c.SetRechargeSnapshot(*v)
	}
	return _c
}

// SetUsageSnapshot sets the "usage_snapshot" field.
func (_c *CheckInRecordCreate) SetUsageSnapshot(v float64) *CheckInRecordCreate {
	_c.mutation.SetUsageSnapshot(v)
	return _c
}

// SetNillableUsageSnapshot sets the "usage_snapshot" field if the given value is not nil.
func (_c *CheckInRecordCreate) SetNillableUsageSnapshot(v *float64) *CheckInRecordCreate {
	if v != nil {
		_c.SetUsageSnapshot(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CheckInRecordCreate) SetCreatedAt(v time.Time) *CheckInRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CheckInRecordCreate) SetNillableCreatedAt(v *time.Time) *CheckInRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CheckInRecordMutation object of the builder.
func (_c *CheckInRecordCreate) Mutation() *CheckInRecordMutation {
	return _c.mutation
}

// Save creates the CheckInRecord in the database.
func (_c *CheckInRecordCreate) Save(ctx context.Context) (*CheckInRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheckInRecordCreate) SaveX(ctx context.Context) *CheckInRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckInRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckInRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheckInRecordCreate) defaults() {
	if _, ok := _c.mutation.RewardAmount(); !ok {
		v := checkinrecord.DefaultRewardAmount
		_c.mutation.SetRewardAmount(v)
	}
	if _, ok := _c.mutation.StreakCount(); !ok {
		v := checkinrecord.DefaultStreakCount
		_c.mutation.SetStreakCount(v)
	}
	if _, ok := _c.mutation.Score(); !ok {
		v := checkinrecord.DefaultScore
		_c.mutation.SetScore(v)
	}
	if _, ok := _c.mutation.RechargeSnapshot(); !ok {
		v := checkinrecord.DefaultRechargeSnapshot
		_c.mutation.SetRechargeSnapshot(v)
	}
	if _, ok := _c.mutation.UsageSnapshot(); !ok {
		v := checkinrecord.DefaultUsageSnapshot
		_c.mutation.SetUsageSnapshot(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := checkinrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheckInRecordCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CheckInRecord.user_id"`)}
	}
	if _, ok := _c.mutation.CheckInDate(); !ok {
		return &ValidationError{Name: "check_in_date", err: errors.New(`ent: missing required field "CheckInRecord.check_in_date"`)}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "CheckInRecord.reward_amount"`)}
	}
	if _, ok := _c.mutation.StreakCount(); !ok {
		return &ValidationError{Name: "streak_count", err: errors.New(`ent: missing required field "CheckInRecord.streak_count"`)}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "CheckInRecord.score"`)}
	}
	if _, ok := _c.mutation.RechargeSnapshot(); !ok {
		return &ValidationError{Name: "recharge_snapshot", err: errors.New(`ent: missing required field "CheckInRecord.recharge_snapshot"`)}
	}
	if _, ok := _c.mutation.UsageSnapshot(); !ok {
		return &ValidationError{Name: "usage_snapshot", err: errors.New(`ent: missing required field "CheckInRecord.usage_snapshot"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CheckInRecord.created_at"`)}
	}
	return nil
}

func (_c *CheckInRecordCreate) sqlSave(ctx context.Context) (*CheckInRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheckInRecordCreate) createSpec() (*CheckInRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckInRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checkinrecord.Table, sqlgraph.NewFieldSpec(checkinrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(checkinrecord.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.CheckInDate(); ok {
		_spec.SetField(checkinrecord.FieldCheckInDate, field.TypeTime, value)
		_node.CheckInDate = value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(checkinrecord.FieldRewardAmount, field.TypeFloat64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.StreakCount(); ok {
		_spec.SetField(checkinrecord.FieldStreakCount, field.TypeInt, value)
		_node.StreakCount = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(checkinrecord.FieldScore, field.TypeFloat64, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.RechargeSnapshot(); ok {
		_spec.SetField(checkinrecord.FieldRechargeSnapshot, field.TypeFloat64, value)
		_node.RechargeSnapshot = value
	}
	if value, ok := _c.mutation.UsageSnapshot(); ok {
		_spec.SetField(checkinrecord.FieldUsageSnapshot, field.TypeFloat64, value)
		_node.UsageSnapshot = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(checkinrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckInRecord.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckInRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckInRecordCreate) OnConflict(opts ...sql.ConflictOption) *CheckInRecordUpsertOne {
	_c.conflict = opts
	return &CheckInRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckInRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckInRecordCreate) OnConflictColumns(columns ...string) *CheckInRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckInRecordUpsertOne{
		create: _c,
	}
}

type (
	// CheckInRecordUpsertOne is the builder for "upsert"-ing
	//  one CheckInRecord node.
	CheckInRecordUpsertOne struct {
		create *CheckInRecordCreate
	}

	// CheckInRecordUpsert is the "OnConflict" setter.
	CheckInRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CheckInRecordUpsert) SetUserID(v int64) *CheckInRecordUpsert {
	u.Set(checkinrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckInRecordUpsert) UpdateUserID() *CheckInRecordUpsert {
	u.SetExcluded(checkinrecord.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CheckInRecordUpsert) AddUserID(v int64) *CheckInRecordUpsert {
	u.Add(checkinrecord.FieldUserID, v)
	return u
}

// SetCheckInDate sets the "check_in_date" field.
func (u *CheckInRecordUpsert) SetCheckInDate(v time.Time) *CheckInRecordUpsert {
	u.Set(checkinrecord.FieldCheckInDate, v)
	return u
}

// UpdateCheckInDate sets the "check_in_date" field to the value that was provided on create.
func (u *CheckInRecordUpsert) UpdateCheckInDate() *CheckInRecordUpsert {
	u.SetExcluded(checkinrecord.FieldCheckInDate)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *CheckInRecordUpsert) SetRewardAmount(v float64) *CheckInRecordUpsert {
	u.Set(checkinrecord.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *CheckInRecordUpsert) UpdateRewardAmount() *CheckInRecordUpsert {
	u.SetExcluded(checkinrecord.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *CheckInRecordUpsert) AddRewardAmount(v float64) *CheckInRecordUpsert {
	u.Add(checkinrecord.FieldRewardAmount, v)
	return u
}

// SetStreakCount sets the "streak_count" field.
func (u *CheckInRecordUpsert) SetStreakCount(v int) *CheckInRecordUpsert {
	u.Set(checkinrecord.FieldStreakCount, v)
	return u
}

// UpdateStreakCount sets the "streak_count" field to the value that was provided on create.
func (u *CheckInRecordUpsert) UpdateStreakCount() *CheckInRecordUpsert {
	u.SetExcluded(checkinrecord.FieldStreakCount)
	return u
}

// AddStreakCount adds v to the "streak_count" field.
func (u *CheckInRecordUpsert) AddStreakCount(v int) *CheckInRecordUpsert {
	u.Add(checkinrecord.FieldStreakCount, v)
	return u
}

// SetScore sets the "score" field.
func (u *CheckInRecordUpsert) SetScore(v float64) *CheckInRecordUpsert {
	u.Set(checkinrecord.FieldScore, v)
	return u
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *CheckInRecordUpsert) UpdateScore() *CheckInRecordUpsert {
	u.SetExcluded(checkinrecord.FieldScore)
	return u
}

// AddScore adds v to the "score" field.
func (u *CheckInRecordUpsert) AddScore(v float64) *CheckInRecordUpsert {
	u.Add(checkinrecord.FieldScore, v)
	return u
}

// SetRechargeSnapshot sets the "recharge_snapshot" field.
func (u *CheckInRecordUpsert) SetRechargeSnapshot(v float64) *CheckInRecordUpsert {
	u.Set(checkinrecord.FieldRechargeSnapshot, v)
	return u
}

// UpdateRechargeSnapshot sets the "recharge_snapshot" field to the value that was provided on create.
func (u *CheckInRecordUpsert) UpdateRechargeSnapshot() *CheckInRecordUpsert {
	u.SetExcluded(checkinrecord.FieldRechargeSnapshot)
	return u
}

// AddRechargeSnapshot adds v to the "recharge_snapshot" field.
func (u *CheckInRecordUpsert) AddRechargeSnapshot(v float64) *CheckInRecordUpsert {
	u.Add(checkinrecord.FieldRechargeSnapshot, v)
	return u
}

// SetUsageSnapshot sets the "usage_snapshot" field.
func (u *CheckInRecordUpsert) SetUsageSnapshot(v float64) *CheckInRecordUpsert {
	u.Set(checkinrecord.FieldUsageSnapshot, v)
	return u
}

// UpdateUsageSnapshot sets the "usage_snapshot" field to the value that was provided on create.
func (u *CheckInRecordUpsert) UpdateUsageSnapshot() *CheckInRecordUpsert {
	u.SetExcluded(checkinrecord.FieldUsageSnapshot)
	return u
}

// AddUsageSnapshot adds v to the "usage_snapshot" field.
func (u *CheckInRecordUpsert) AddUsageSnapshot(v float64) *CheckInRecordUpsert {
	u.Add(checkinrecord.FieldUsageSnapshot, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CheckInRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckInRecordUpsertOne) UpdateNewValues() *CheckInRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(checkinrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckInRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CheckInRecordUpsertOne) Ignore() *CheckInRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckInRecordUpsertOne) DoNothing() *CheckInRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckInRecordCreate.OnConflict
// documentation for more info.
func (u *CheckInRecordUpsertOne) Update(set func(*CheckInRecordUpsert)) *CheckInRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckInRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckInRecordUpsertOne) SetUserID(v int64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CheckInRecordUpsertOne) AddUserID(v int64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckInRecordUpsertOne) UpdateUserID() *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckInDate sets the "check_in_date" field.
func (u *CheckInRecordUpsertOne) SetCheckInDate(v time.Time) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetCheckInDate(v)
	})
}

// UpdateCheckInDate sets the "check_in_date" field to the value that was provided on create.
func (u *CheckInRecordUpsertOne) UpdateCheckInDate() *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateCheckInDate()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *CheckInRecordUpsertOne) SetRewardAmount(v float64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *CheckInRecordUpsertOne) AddRewardAmount(v float64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *CheckInRecordUpsertOne) UpdateRewardAmount() *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStreakCount sets the "streak_count" field.
func (u *CheckInRecordUpsertOne) SetStreakCount(v int) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetStreakCount(v)
	})
}

// AddStreakCount adds v to the "streak_count" field.
func (u *CheckInRecordUpsertOne) AddStreakCount(v int) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddStreakCount(v)
	})
}

// UpdateStreakCount sets the "streak_count" field to the value that was provided on create.
func (u *CheckInRecordUpsertOne) UpdateStreakCount() *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateStreakCount()
	})
}

// SetScore sets the "score" field.
func (u *CheckInRecordUpsertOne) SetScore(v float64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *CheckInRecordUpsertOne) AddScore(v float64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *CheckInRecordUpsertOne) UpdateScore() *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateScore()
	})
}

// SetRechargeSnapshot sets the "recharge_snapshot" field.
func (u *CheckInRecordUpsertOne) SetRechargeSnapshot(v float64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetRechargeSnapshot(v)
	})
}

// AddRechargeSnapshot adds v to the "recharge_snapshot" field.
func (u *CheckInRecordUpsertOne) AddRechargeSnapshot(v float64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddRechargeSnapshot(v)
	})
}

// UpdateRechargeSnapshot sets the "recharge_snapshot" field to the value that was provided on create.
func (u *CheckInRecordUpsertOne) UpdateRechargeSnapshot() *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateRechargeSnapshot()
	})
}

// SetUsageSnapshot sets the "usage_snapshot" field.
func (u *CheckInRecordUpsertOne) SetUsageSnapshot(v float64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetUsageSnapshot(v)
	})
}

// AddUsageSnapshot adds v to the "usage_snapshot" field.
func (u *CheckInRecordUpsertOne) AddUsageSnapshot(v float64) *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddUsageSnapshot(v)
	})
}

// UpdateUsageSnapshot sets the "usage_snapshot" field to the value that was provided on create.
func (u *CheckInRecordUpsertOne) UpdateUsageSnapshot() *CheckInRecordUpsertOne {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateUsageSnapshot()
	})
}

// Exec executes the query.
func (u *CheckInRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckInRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckInRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CheckInRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CheckInRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CheckInRecordCreateBulk is the builder for creating many CheckInRecord entities in bulk.
type CheckInRecordCreateBulk struct {
	config
	err      error
	builders []*CheckInRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the CheckInRecord entities in the database.
func (_c *CheckInRecordCreateBulk) Save(ctx context.Context) ([]*CheckInRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CheckInRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckInRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheckInRecordCreateBulk) SaveX(ctx context.Context) []*CheckInRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckInRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckInRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckInRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckInRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckInRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *CheckInRecordUpsertBulk {
	_c.conflict = opts
	return &CheckInRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckInRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckInRecordCreateBulk) OnConflictColumns(columns ...string) *CheckInRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckInRecordUpsertBulk{
		create: _c,
	}
}

// CheckInRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of CheckInRecord nodes.
type CheckInRecordUpsertBulk struct {
	create *CheckInRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CheckInRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckInRecordUpsertBulk) UpdateNewValues() *CheckInRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(checkinrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckInRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CheckInRecordUpsertBulk) Ignore() *CheckInRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckInRecordUpsertBulk) DoNothing() *CheckInRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckInRecordCreateBulk.OnConflict
// documentation for more info.
func (u *CheckInRecordUpsertBulk) Update(set func(*CheckInRecordUpsert)) *CheckInRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckInRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckInRecordUpsertBulk) SetUserID(v int64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CheckInRecordUpsertBulk) AddUserID(v int64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckInRecordUpsertBulk) UpdateUserID() *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckInDate sets the "check_in_date" field.
func (u *CheckInRecordUpsertBulk) SetCheckInDate(v time.Time) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetCheckInDate(v)
	})
}

// UpdateCheckInDate sets the "check_in_date" field to the value that was provided on create.
func (u *CheckInRecordUpsertBulk) UpdateCheckInDate() *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateCheckInDate()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *CheckInRecordUpsertBulk) SetRewardAmount(v float64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *CheckInRecordUpsertBulk) AddRewardAmount(v float64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *CheckInRecordUpsertBulk) UpdateRewardAmount() *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStreakCount sets the "streak_count" field.
func (u *CheckInRecordUpsertBulk) SetStreakCount(v int) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetStreakCount(v)
	})
}

// AddStreakCount adds v to the "streak_count" field.
func (u *CheckInRecordUpsertBulk) AddStreakCount(v int) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddStreakCount(v)
	})
}

// UpdateStreakCount sets the "streak_count" field to the value that was provided on create.
func (u *CheckInRecordUpsertBulk) UpdateStreakCount() *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateStreakCount()
	})
}

// SetScore sets the "score" field.
func (u *CheckInRecordUpsertBulk) SetScore(v float64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *CheckInRecordUpsertBulk) AddScore(v float64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *CheckInRecordUpsertBulk) UpdateScore() *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateScore()
	})
}

// SetRechargeSnapshot sets the "recharge_snapshot" field.
func (u *CheckInRecordUpsertBulk) SetRechargeSnapshot(v float64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetRechargeSnapshot(v)
	})
}

// AddRechargeSnapshot adds v to the "recharge_snapshot" field.
func (u *CheckInRecordUpsertBulk) AddRechargeSnapshot(v float64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddRechargeSnapshot(v)
	})
}

// UpdateRechargeSnapshot sets the "recharge_snapshot" field to the value that was provided on create.
func (u *CheckInRecordUpsertBulk) UpdateRechargeSnapshot() *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateRechargeSnapshot()
	})
}

// SetUsageSnapshot sets the "usage_snapshot" field.
func (u *CheckInRecordUpsertBulk) SetUsageSnapshot(v float64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.SetUsageSnapshot(v)
	})
}

// AddUsageSnapshot adds v to the "usage_snapshot" field.
func (u *CheckInRecordUpsertBulk) AddUsageSnapshot(v float64) *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.AddUsageSnapshot(v)
	})
}

// UpdateUsageSnapshot sets the "usage_snapshot" field to the value that was provided on create.
func (u *CheckInRecordUpsertBulk) UpdateUsageSnapshot() *CheckInRecordUpsertBulk {
	return u.Update(func(s *CheckInRecordUpsert) {
		s.UpdateUsageSnapshot()
	})
}

// Exec executes the query.
func (u *CheckInRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CheckInRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckInRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckInRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
